---
#============================================================================================================
# Ansible internal
#============================================================================================================
# This are ansible specific variables that need to be present
ansible_become_pass:  "{{ secrets.ans_sudo_pw }}"
ansible_user: "{{ autobott_enroll.user }}"

#============================================================================================================
# Enroll system
#============================================================================================================
autobott_enroll:
  # Ansible login user
  user: ans
  # used by ansible to escalate to root once logged in this is defined when we enroll the system
  passwd:  "{{ secrets.ans_sudo_pw }}"
  # User keys allowed to login as ansible admin, thus run ansible playbook
  ssh_keys:
    - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDv0lp74sCQJIrreeyRIFsghhH5696soRK3A0tVs3ZzC ans@autobott"

#============================================================================================================
# Linux apt
#============================================================================================================
run_role_linux_apt: true
linux_apt:
  release: "bookworm"
  use_contrib: true
  use_nonfree: false
  use_backports: true
  automatic_updates: true # setting this to yes will make the vagrant task to fail because of lock on dpkg

#============================================================================================================
# Linux Basics
#============================================================================================================
run_role_linux_basic: true
linux_basic:
  cron_email: "me@example.com"
  packages:
    host_defined:
      - htop
      - btop
  hostname: "ansible-autobott-example"

  ssh:
    sftp_jails:
      - group_name: sftp
        jail_dir: "/vhosts"
        start_dir: "/home_dir" # optional, allows to define the default starting dir when opening a session
        umask: "0037"            # change the umask parameter of the jail default is 0037 creates files as 0750
        allow_password: true
        remove: false # set to true to remove the sftp jail config

  groups:
    - name: smbmedia
    - name: sftp

  system_users:
    - username: "smbmedia"
      enabled: true
      name: "shared samba media"
      groups: ["smbmedia"]
      uid: 800
      gid: 800

  users:
    - username: jsmith
      enabled: true
      delete_home: false
      uid: 2002
      name: "The Doctor"
      primary_group: "users"
      groups: ["sudo" ]
      password: "{{ secrets.users.jsmith.password}}"
      shell: /bin/bash # optional

