#============================================================================================================
# Lynis audit
#============================================================================================================
run_role_lynis: False

#============================================================================================================
# Firewall
#============================================================================================================
run_role_firewall: True
firewall:
  allowed_outbound_tcp:
    - 22  # ssh used by borg
    - 465 # used to send emails
  allow_docker: False

#============================================================================================================
# Malware scan
#============================================================================================================
run_role_malwarescan: False

#============================================================================================================
# Authelia
#============================================================================================================
run_role_authelia: True
authelia:

  secrets:
    # needs to be more than 20 chars
    storage_encryption_key: "{{ secrets.services.authelia.storage_key }}"
    session:  "{{ secrets.services.authelia.session }}"

  sites:
    - domain: "ansible-autobott-example.lan"
      policy: "two_factor" # one_factor | two_factor
      groups:
        - homepage

    - domain:
        - "prowlarr.ansible-autobott-example.lan"
        - "lidarr.ansible-autobott-example.lan"
        - "radarr.ansible-autobott-example.lan"
        - "readarr.ansible-autobott-example.lan"
        - "sonarr.ansible-autobott-example.lan"
        - "romm.ansible-autobott-example.lan"
        - "whisparr.ansible-autobott-example.lan"
        - "stash.ansible-autobott-example.lan"
        - "xbvr.ansible-autobott-example.lan"
        - "transmission.ansible-autobott-example.lan"

      policy: "one_factor" # one_factor | two_factor
      groups:
        - servarr

  timeout:
    # The period of time the user can be inactive for until the session is destroyed
    inactivity: '10m'
    # The period of time before the cookie expires and the session is destroyed.
    expiration: '1h'
    # The period of time before the cookie expires and the session is destroyed when the remember me box is checked
    remember_me: '1M'

  cookies:
    - name: "authelia_session"
      domain: "ansible-autobott-example.lan"
      authelia_url: "https://auth.ansible-autobott-example.lan"

  users:
    - username: demo
      displayname: "demo"
      password: "{{ secrets.services.authelia.users.demo.password }}"
      salt: "{{ secrets.services.authelia.users.demo.salt }}"
      email: "me@example.com"
      groups:
        - homepage
        - servarr
      disabled: false

  # smtp config used for notifications, e.g. when enabling 2fa
  # this sample uses a fastmail subscription
  smtp:
    address: ""
#    address: "submissions://{{ secrets.email.address}}:{{ secrets.email.port}}"
    timeout: '5s'
    username: "{{ secrets.email.user}}"
    password: "{{ secrets.email.pass}}"
    sender: "Authelia <{{ secrets.email.sender}}>"
    identifier: 'localhost'
