#============================================================================================================
# Transmission
#============================================================================================================
run_role_transmission: true
transmission:
  download:
    path:  "/media/torrent"
    owner: debian-transmission
    group: smbmedia
    mode: "2750"
  umask: 7

#============================================================================================================
# Jellyfin
#============================================================================================================
run_role_jellyfin: true
jellyfin:
  extra_groups:
    - smbmedia
  umask: "0007"

#============================================================================================================
# Kavita
#============================================================================================================
run_role_kavita: true

#============================================================================================================
# Sonarr
#============================================================================================================
run_role_sonarr: true
sonarr:
  user:
    group: smbmedia
  service:
    umask: "0007"

#============================================================================================================
# Prowlarr
#============================================================================================================
run_role_prowlarr: true

#============================================================================================================
# Lidarr
#============================================================================================================
run_role_lidarr: true

#============================================================================================================
# Radarr
#============================================================================================================
run_role_radarr: true

#============================================================================================================
# Readarr
#============================================================================================================
run_role_readarr: true

#============================================================================================================
# Whisparr
#============================================================================================================
run_role_whisparr: true

#============================================================================================================
# Stash
#============================================================================================================
run_role_stash: true

#============================================================================================================
# Xbvr
#============================================================================================================
run_role_xbvr: true

#============================================================================================================
# Romm
#============================================================================================================
run_role_romm: true
romm:
  db_pass: "changeme"
  app_secret: "INSECURE_DEMO!!!!62ccf712c5e6b4db50641031f9df129fbca6df14a960a9d447abb"