#============================================================================================================
# PHP-FPM
#============================================================================================================
run_role_php_fpm: True

#============================================================================================================
# Caddy
#============================================================================================================
run_role_caddy: True
caddy:
  admin: "0.0.0.0:2019"
  email: "me@example.com"



#============================================================================================================
# Homepage
#============================================================================================================
run_role_homepage: True
homepage:
  allowed_host: ansible-autobott-example.lan

