# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Actions:
    - Logout:
        href: https://auth.example.com/logout

- Web:
    - docmost:
          description: Collaborative Wiki
          href: https://wiki.example.com
          icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/docmost.png

    - mealie:
        description: Meal recipes
        href: https://meals.example.com
        icon: mealie.png