---
#============================================================================================================
# Tailscale
#============================================================================================================
run_role_tailscale: False

#============================================================================================================
# Docker
#============================================================================================================
run_role_docker: True
docker:
  expose_metrics: true
  users: [] # users added to the docker group

#============================================================================================================
# MariaDb (mysql)
#============================================================================================================
run_role_mariadb: False
