#============================================================================================================
# Lynis audit
#============================================================================================================
run_role_lynis: False

#============================================================================================================
# Firewall
#============================================================================================================
run_role_firewall: True

#============================================================================================================
# Malware scan
#============================================================================================================
run_role_malwarescan: False