#============================================================================================================
# PHP-FPM
#============================================================================================================
run_role_php_fpm: True

#============================================================================================================
# Caddy
#============================================================================================================
run_role_caddy: True
caddy:
  admin: "0.0.0.0:2019"
  email: "me@example.com"

#============================================================================================================
# Authelia
#============================================================================================================
run_role_authelia: True
authelia:
  sites:
    - domain: "example.com"
      policy: "one_factor" # one_factor | two_factor
      groups:
        - homepage

    - domain: "wiki.example.com"
      policy: "one_factor" # one_factor | two_factor
      groups:
        - wiki

    - domain: "meals.example.com"
      policy: "one_factor" # one_factor | two_factor
      groups:
        - wiki

  cookies:
    - name: "authelia_session"
      domain: "example.com"
      authelia_url: "https://auth.example.com"

  users:
    - username: demo
      displayname: "demo"
      password: "{{ secrets.services.authelia.demo.password }}"
      salt: "{{ secrets.services.authelia.demo.salt }}"
      email: "me@example.com"
      groups:
        - homepage
        - wiki
      disabled: false


#============================================================================================================
# Homepage
#============================================================================================================
run_role_homepage: True
homepage:
  allowed_host: example.com

#============================================================================================================
# Docmost
#============================================================================================================
run_role_docmost: True
docmost:
  app_url: "https://wiki.example.com"
  db_pass: "{{ secrets.services.docmost.db_pass }}"
  app_secret: "{{ secrets.services.docmost.app_secret }}"


#============================================================================================================
# Mealie
#============================================================================================================
run_role_mealie: true
mealie:
  base_url: "https://meals.example.com"
